/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MNEEEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DISPUTE_TIMEOUT"
      | "MAX_EXTENSION"
      | "MIN_AMOUNT"
      | "MNEE_MAINNET"
      | "authorizedAgents"
      | "createEscrow(bytes32,address,uint256,address,uint64,bytes32)"
      | "createEscrow(bytes32,address,uint256,address,uint64)"
      | "dispute"
      | "escrowCount"
      | "escrows"
      | "extendDeadline"
      | "getEscrow"
      | "isAuthorizedAgent"
      | "isExpired"
      | "owner"
      | "pause"
      | "paused"
      | "refund"
      | "release"
      | "releasePartial"
      | "remainingBalance"
      | "renounceOwnership"
      | "resolveDispute"
      | "setAgentAuthorization"
      | "token"
      | "totalValueLocked"
      | "transferOwnership"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentAuthorized"
      | "DeadlineExtended"
      | "DisputeResolved"
      | "EscrowCreated"
      | "EscrowDisputed"
      | "EscrowRefunded"
      | "EscrowReleased"
      | "OwnershipTransferred"
      | "Paused"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DISPUTE_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_EXTENSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MNEE_MAINNET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedAgents",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrow(bytes32,address,uint256,address,uint64,bytes32)",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrow(bytes32,address,uint256,address,uint64)",
    values: [BytesLike, AddressLike, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "dispute", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "escrowCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "escrows", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "extendDeadline",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isExpired",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "refund", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "release", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "releasePartial",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "remainingBalance",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentAuthorization",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalValueLocked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DISPUTE_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_EXTENSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_AMOUNT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MNEE_MAINNET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrow(bytes32,address,uint256,address,uint64,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrow(bytes32,address,uint256,address,uint64)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dispute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "escrowCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "extendDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isExpired", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releasePartial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remainingBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalValueLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace AgentAuthorizedEvent {
  export type InputTuple = [agent: AddressLike, authorized: boolean];
  export type OutputTuple = [agent: string, authorized: boolean];
  export interface OutputObject {
    agent: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeadlineExtendedEvent {
  export type InputTuple = [
    escrowId: BytesLike,
    oldDeadline: BigNumberish,
    newDeadline: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: string,
    oldDeadline: bigint,
    newDeadline: bigint
  ];
  export interface OutputObject {
    escrowId: string;
    oldDeadline: bigint;
    newDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    escrowId: BytesLike,
    resolvedBy: AddressLike,
    releasedToPayee: boolean,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: string,
    resolvedBy: string,
    releasedToPayee: boolean,
    amount: bigint
  ];
  export interface OutputObject {
    escrowId: string;
    resolvedBy: string;
    releasedToPayee: boolean;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    escrowId: BytesLike,
    payer: AddressLike,
    payee: AddressLike,
    arbiter: AddressLike,
    amount: BigNumberish,
    deadline: BigNumberish,
    metadataHash: BytesLike
  ];
  export type OutputTuple = [
    escrowId: string,
    payer: string,
    payee: string,
    arbiter: string,
    amount: bigint,
    deadline: bigint,
    metadataHash: string
  ];
  export interface OutputObject {
    escrowId: string;
    payer: string;
    payee: string;
    arbiter: string;
    amount: bigint;
    deadline: bigint;
    metadataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowDisputedEvent {
  export type InputTuple = [
    escrowId: BytesLike,
    disputedBy: AddressLike,
    disputedAt: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: string,
    disputedBy: string,
    disputedAt: bigint
  ];
  export interface OutputObject {
    escrowId: string;
    disputedBy: string;
    disputedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowRefundedEvent {
  export type InputTuple = [
    escrowId: BytesLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [escrowId: string, to: string, amount: bigint];
  export interface OutputObject {
    escrowId: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowReleasedEvent {
  export type InputTuple = [
    escrowId: BytesLike,
    to: AddressLike,
    amount: BigNumberish,
    remaining: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: string,
    to: string,
    amount: bigint,
    remaining: bigint
  ];
  export interface OutputObject {
    escrowId: string;
    to: string;
    amount: bigint;
    remaining: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MNEEEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): MNEEEscrow;
  waitForDeployment(): Promise<this>;

  interface: MNEEEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DISPUTE_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  MAX_EXTENSION: TypedContractMethod<[], [bigint], "view">;

  MIN_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  MNEE_MAINNET: TypedContractMethod<[], [string], "view">;

  authorizedAgents: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  "createEscrow(bytes32,address,uint256,address,uint64,bytes32)": TypedContractMethod<
    [
      escrowId: BytesLike,
      payee: AddressLike,
      amount: BigNumberish,
      arbiter: AddressLike,
      deadline: BigNumberish,
      metadataHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  "createEscrow(bytes32,address,uint256,address,uint64)": TypedContractMethod<
    [
      escrowId: BytesLike,
      payee: AddressLike,
      amount: BigNumberish,
      arbiter: AddressLike,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  dispute: TypedContractMethod<[escrowId: BytesLike], [void], "nonpayable">;

  escrowCount: TypedContractMethod<[], [bigint], "view">;

  escrows: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        payer: string;
        payee: string;
        arbiter: string;
        amount: bigint;
        released: bigint;
        deadline: bigint;
        disputedAt: bigint;
        status: bigint;
        metadataHash: string;
      }
    ],
    "view"
  >;

  extendDeadline: TypedContractMethod<
    [escrowId: BytesLike, extension: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEscrow: TypedContractMethod<
    [escrowId: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        payer: string;
        payee: string;
        arbiter: string;
        amount: bigint;
        released: bigint;
        deadline: bigint;
        disputedAt: bigint;
        status: bigint;
        metadataHash: string;
      }
    ],
    "view"
  >;

  isAuthorizedAgent: TypedContractMethod<
    [agent: AddressLike],
    [boolean],
    "view"
  >;

  isExpired: TypedContractMethod<[escrowId: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  refund: TypedContractMethod<[escrowId: BytesLike], [void], "nonpayable">;

  release: TypedContractMethod<[escrowId: BytesLike], [void], "nonpayable">;

  releasePartial: TypedContractMethod<
    [escrowId: BytesLike, partialAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  remainingBalance: TypedContractMethod<
    [escrowId: BytesLike],
    [bigint],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveDispute: TypedContractMethod<
    [escrowId: BytesLike, releaseToPayee: boolean],
    [void],
    "nonpayable"
  >;

  setAgentAuthorization: TypedContractMethod<
    [agent: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  totalValueLocked: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DISPUTE_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_EXTENSION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MNEE_MAINNET"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "authorizedAgents"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "createEscrow(bytes32,address,uint256,address,uint64,bytes32)"
  ): TypedContractMethod<
    [
      escrowId: BytesLike,
      payee: AddressLike,
      amount: BigNumberish,
      arbiter: AddressLike,
      deadline: BigNumberish,
      metadataHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createEscrow(bytes32,address,uint256,address,uint64)"
  ): TypedContractMethod<
    [
      escrowId: BytesLike,
      payee: AddressLike,
      amount: BigNumberish,
      arbiter: AddressLike,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dispute"
  ): TypedContractMethod<[escrowId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "escrowCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        payer: string;
        payee: string;
        arbiter: string;
        amount: bigint;
        released: bigint;
        deadline: bigint;
        disputedAt: bigint;
        status: bigint;
        metadataHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "extendDeadline"
  ): TypedContractMethod<
    [escrowId: BytesLike, extension: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [escrowId: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        payer: string;
        payee: string;
        arbiter: string;
        amount: bigint;
        released: bigint;
        deadline: bigint;
        disputedAt: bigint;
        status: bigint;
        metadataHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAuthorizedAgent"
  ): TypedContractMethod<[agent: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isExpired"
  ): TypedContractMethod<[escrowId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[escrowId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<[escrowId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releasePartial"
  ): TypedContractMethod<
    [escrowId: BytesLike, partialAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "remainingBalance"
  ): TypedContractMethod<[escrowId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [escrowId: BytesLike, releaseToPayee: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgentAuthorization"
  ): TypedContractMethod<
    [agent: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalValueLocked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AgentAuthorized"
  ): TypedContractEvent<
    AgentAuthorizedEvent.InputTuple,
    AgentAuthorizedEvent.OutputTuple,
    AgentAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "DeadlineExtended"
  ): TypedContractEvent<
    DeadlineExtendedEvent.InputTuple,
    DeadlineExtendedEvent.OutputTuple,
    DeadlineExtendedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowDisputed"
  ): TypedContractEvent<
    EscrowDisputedEvent.InputTuple,
    EscrowDisputedEvent.OutputTuple,
    EscrowDisputedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowRefunded"
  ): TypedContractEvent<
    EscrowRefundedEvent.InputTuple,
    EscrowRefundedEvent.OutputTuple,
    EscrowRefundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowReleased"
  ): TypedContractEvent<
    EscrowReleasedEvent.InputTuple,
    EscrowReleasedEvent.OutputTuple,
    EscrowReleasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AgentAuthorized(address,bool)": TypedContractEvent<
      AgentAuthorizedEvent.InputTuple,
      AgentAuthorizedEvent.OutputTuple,
      AgentAuthorizedEvent.OutputObject
    >;
    AgentAuthorized: TypedContractEvent<
      AgentAuthorizedEvent.InputTuple,
      AgentAuthorizedEvent.OutputTuple,
      AgentAuthorizedEvent.OutputObject
    >;

    "DeadlineExtended(bytes32,uint64,uint64)": TypedContractEvent<
      DeadlineExtendedEvent.InputTuple,
      DeadlineExtendedEvent.OutputTuple,
      DeadlineExtendedEvent.OutputObject
    >;
    DeadlineExtended: TypedContractEvent<
      DeadlineExtendedEvent.InputTuple,
      DeadlineExtendedEvent.OutputTuple,
      DeadlineExtendedEvent.OutputObject
    >;

    "DisputeResolved(bytes32,address,bool,uint256)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "EscrowCreated(bytes32,address,address,address,uint256,uint64,bytes32)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "EscrowDisputed(bytes32,address,uint64)": TypedContractEvent<
      EscrowDisputedEvent.InputTuple,
      EscrowDisputedEvent.OutputTuple,
      EscrowDisputedEvent.OutputObject
    >;
    EscrowDisputed: TypedContractEvent<
      EscrowDisputedEvent.InputTuple,
      EscrowDisputedEvent.OutputTuple,
      EscrowDisputedEvent.OutputObject
    >;

    "EscrowRefunded(bytes32,address,uint256)": TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;
    EscrowRefunded: TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;

    "EscrowReleased(bytes32,address,uint256,uint256)": TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
    EscrowReleased: TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
